name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t my-app .
    - name: Run Docker image
      run: docker run -d -p 3000:3000 my-app
    - name: Test
      run: curl localhost:3000
